name: geocat_comp_build
channels:
  - conda-forge
  - ncar
dependencies:
  - python=3.7
  - cf_xarray>=0.3.1
  - dask
  - distributed
  - eofs
  - geocat-datafiles  # for tests
  - geocat-f2py
  - netcdf4  # for tests
  - numpy
  - pytest  # for tests
  - xarray
