import sys

import geocat.datafiles as gdf
import numpy as np
import numpy.testing as nt
import xarray as xr
import pytest

from geocat.comp import interp_multidim, interp_hybrid_to_pressure, interp_sigma_to_hybrid

# Global input data

# Open the netCDF data file "atmos.nc" and read in common variables
try:
    ds_atmos = xr.open_dataset(gdf.get("netcdf_files/atmos.nc"),
                               decode_times=False)
except:
    ds_atmos = xr.open_dataset("test/atmos.nc", decode_times=False)

_hyam = ds_atmos.hyam
_hybm = ds_atmos.hybm
_p0 = 1000. * 100  # Pa


class Test_interp_hybrid_to_pressure:

    # Expected output from above sample input
    @pytest.fixture(scope="class")
    def ds_out(self):
        try:
            return xr.open_dataset(
                "vinth2p_output.nc"
            )  # Generated by running ncl_tests/vinth2p_test_conwomap_5.ncl on
        # atmos.nc
        except:
            return xr.open_dataset("test/vinth2p_output.nc")

    @pytest.fixture(autouse=True, scope="class")
    def setUpClass(self, ds_out) -> None:
        # @classmethod will fail python3.9 CI due to pytest bug (pytest-dev Issue 3778), fix: cls -> self.__class__
        # Sample input data
        self.__class__.data = ds_atmos.U[0, :, :, :]
        self.__class__.ps = ds_atmos.PS
        self.__class__.pres3d = np.asarray(
            [1000, 950, 800, 700, 600, 500, 400, 300, 200])  # mb
        self.__class__.pres3d = self.__class__.pres3d * 100  # mb to Pa
        self.__class__.uzon_expected = ds_out.uzon  # Expected output
        self.__class__.u_int_expected = ds_out.u_int  # Expected output

    def test_interp_hybrid_to_pressure_atmos(self) -> None:
        u_int = interp_hybrid_to_pressure(self.data,
                                          self.ps[0, :, :],
                                          _hyam,
                                          _hybm,
                                          p0=_p0,
                                          new_levels=self.pres3d,
                                          method="log")

        uzon = u_int.mean(dim='lon')

        nt.assert_array_almost_equal(self.uzon_expected, uzon, 5)

    def test_interp_hybrid_to_pressure_atmos_4d(self) -> None:
        data_t = self.data.expand_dims("time")

        u_int = interp_hybrid_to_pressure(data_t,
                                          self.ps,
                                          _hyam,
                                          _hybm,
                                          p0=_p0,
                                          new_levels=self.pres3d,
                                          method="log")

        uzon = u_int.mean(dim='lon')

        uzon_expected_t = self.uzon_expected.expand_dims("time")
        nt.assert_array_almost_equal(uzon_expected_t, uzon, 5)

    def test_interp_hybrid_to_pressure_atmos_wrong_method(self) -> None:
        with pytest.raises(ValueError):
            u_int = interp_hybrid_to_pressure(self.data,
                                              self.ps[0, :, :],
                                              _hyam,
                                              _hybm,
                                              p0=_p0,
                                              new_levels=self.pres3d,
                                              method="wrong_method")

    def test_interp_hybrid_to_pressure_atmos_dask(self) -> None:

        ps_dask = self.ps.chunk()
        data_dask = self.data.chunk()

        u_int = interp_hybrid_to_pressure(data_dask,
                                          ps_dask[0, :, :],
                                          _hyam,
                                          _hybm,
                                          p0=_p0,
                                          new_levels=self.pres3d,
                                          method="log")

        uzon = u_int.mean(dim='lon')

        nt.assert_array_almost_equal(self.uzon_expected, uzon, 5)


class Test_interp_hybrid_to_pressure_extrapolate:

    @pytest.fixture(scope="class")
    def ds_ccsm(self):
        # Open the netCDF data file with the input data
        try:
            return xr.open_dataset(
                gdf.get("netcdf_files/ccsm35.h0.0021-01.demo.nc"),
                decode_times=False)
        except:
            return xr.open_dataset("test/ccsm35.h0.0021-01.demo.nc",
                                   decode_times=False)

    @pytest.fixture(scope="class")
    def ds_out(self):
        # Open the netCDF file with the output data from running vinth2p_ecmwf.ncl
        try:
            return xr.open_dataset("test/vinth2p_ecmwf_output.nc",
                                   decode_times=False)
        except:
            return xr.open_dataset("vinth2p_ecmwf_output.nc",
                                   decode_times=False)

    @pytest.fixture(autouse=True, scope="class")
    @classmethod
    def setUpClass(cls, ds_ccsm, ds_out) -> None:
        # Pull out inputs
        cls._hyam = ds_ccsm.hyam
        cls._hybm = ds_ccsm.hybm
        cls.temp_in = ds_ccsm.T[:, :, :3, :2]
        cls.t_bot = ds_ccsm.TS[:, :3, :2]
        cls.geopotential_in = ds_ccsm.Z3[:, :, :3, :2]
        cls.humidity_in = ds_ccsm.Q[:, :, :3, :2] * 1000  # g/kg
        cls.press_in = ds_ccsm.PS[:, :3, :2]
        cls.phis = ds_ccsm.PHIS[:, :3, :2]

        cls.temp_interp_expected = ds_out.Tp.rename(lev_p='plev')
        cls.temp_extrap_expected = ds_out.Tpx.rename(lev_p='plev')
        cls.geopotential_extrap_expected = ds_out.Zpx.rename(lev_p='plev')
        cls.humidity_extrap_expected = ds_out.Qpx.rename(lev_p='plev')

        cls.new_levels = np.asarray([500, 925, 950, 1000])
        cls.new_levels *= 100  # new levels in Pa
        cls._p0 = 1000 * 100  # reference pressure in Pa

    def test_interp_hybrid_to_pressure_interp_temp(self) -> None:
        result = interp_hybrid_to_pressure(self.temp_in,
                                           self.press_in,
                                           self._hyam,
                                           self._hybm,
                                           p0=self._p0,
                                           new_levels=self.new_levels,
                                           method="linear")
        result = result.transpose('time', 'plev', 'lat', 'lon')
        result = result.assign_coords(dict(plev=self.new_levels / 100))
        xr.testing.assert_allclose(self.temp_interp_expected, result)

    def test_interp_hybrid_to_pressure_extrap_temp(self) -> None:
        result = interp_hybrid_to_pressure(self.temp_in,
                                           self.press_in,
                                           self._hyam,
                                           self._hybm,
                                           p0=self._p0,
                                           new_levels=self.new_levels,
                                           method="linear",
                                           extrapolate=True,
                                           variable='temperature',
                                           t_bot=self.t_bot,
                                           phi_sfc=self.phis)
        result = result.transpose('time', 'plev', 'lat', 'lon')
        result = result.assign_coords(dict(plev=self.new_levels / 100))
        xr.testing.assert_allclose(self.temp_extrap_expected, result)

    def test_interp_hybrid_to_pressure_extrap_geopotential(self) -> None:
        result = interp_hybrid_to_pressure(self.geopotential_in,
                                           self.press_in,
                                           self._hyam,
                                           self._hybm,
                                           p0=self._p0,
                                           new_levels=self.new_levels,
                                           method="linear",
                                           extrapolate=True,
                                           variable='geopotential',
                                           t_bot=self.t_bot,
                                           phi_sfc=self.phis)
        result = result.transpose('time', 'plev', 'lat', 'lon')
        result = result.assign_coords(dict(plev=self.new_levels / 100))
        xr.testing.assert_allclose(self.geopotential_extrap_expected, result)

    def test_interp_hybrid_to_pressure_extrap_other(self) -> None:
        result = interp_hybrid_to_pressure(self.humidity_in,
                                           self.press_in,
                                           self._hyam,
                                           self._hybm,
                                           p0=self._p0,
                                           new_levels=self.new_levels,
                                           method="linear",
                                           extrapolate=True,
                                           variable='other',
                                           t_bot=self.t_bot,
                                           phi_sfc=self.phis)
        result = result.transpose('time', 'plev', 'lat', 'lon')
        result = result.assign_coords(dict(plev=self.new_levels / 100))
        xr.testing.assert_allclose(self.humidity_extrap_expected, result)

    def test_interp_hybrid_to_pressure_extrap_kwargs(self) -> None:
        with pytest.raises(ValueError):
            interp_hybrid_to_pressure(self.humidity_in,
                                      self.press_in,
                                      self._hyam,
                                      self._hybm,
                                      p0=self._p0,
                                      new_levels=self.new_levels,
                                      method="linear",
                                      extrapolate=True)

    def test_interp_hybrid_to_pressure_extrap_invalid_var(self) -> None:
        with pytest.raises(ValueError):
            interp_hybrid_to_pressure(self.humidity_in,
                                      self.press_in,
                                      self._hyam,
                                      self._hybm,
                                      p0=self._p0,
                                      new_levels=self.new_levels,
                                      method="linear",
                                      extrapolate=True,
                                      variable=' ',
                                      t_bot=self.t_bot,
                                      phi_sfc=self.phis)


class Test_interp_sigma_to_hybrid:

    @pytest.fixture(scope="class")
    def ds_u(self):
        # Open the netCDF data file "u.89335.1.nc" and read in input data
        try:
            return xr.open_dataset(
                gdf.get("netcdf_files/u.89335.1_subset_time361.nc"),
                decode_times=False)
        except:
            return xr.open_dataset("test/u.89335.1_subset_time361.nc",
                                   decode_times=False)

    @pytest.fixture(scope="class")
    def ds_ps(self):
        # Open the netCDF data file "ps.89335.1.nc" and read in additional input
        # data
        try:
            return xr.open_dataset(gdf.get("netcdf_files/ps.89335.1.nc"),
                                   decode_times=False)
        except:
            return xr.open_dataset("test/ps.89335.1.nc", decode_times=False)

    @pytest.fixture(scope="class")
    def ds_out(self):
        # Expected output from above sample input
        try:
            return xr.open_dataset(
                "sigma2hybrid_output.nc"
            )  # Generated by running ncl_tests/test_sigma2hybrid.ncl
        except:
            return xr.open_dataset("test/sigma2hybrid_output.nc")

    @pytest.fixture(autouse=True, scope="class")
    @classmethod
    def setUpClass(cls, ds_u, ds_ps, ds_out) -> None:
        cls.hyam = xr.DataArray([0.0108093, 0.0130731, 0.03255911, 0.0639471])
        cls.hybm = xr.DataArray([0.0108093, 0.0173664, 0.06069280, 0.1158237])
        cls.u = ds_u.u[:, 0:3, 0:2]
        cls.ps = ds_ps.ps[361, 0:3, 0:2] * 100  # Pa
        cls.sigma = ds_ps.sigma
        cls.xh_expected = ds_out.xh.transpose("ncl3", "ncl1",
                                              "ncl2")  # Expected output

    def test_interp_sigma_to_hybrid_1d(self) -> None:
        xh = interp_sigma_to_hybrid(self.u[:, 0, 0],
                                    self.sigma,
                                    self.ps[0, 0],
                                    self.hyam,
                                    self.hybm,
                                    p0=_p0,
                                    method="linear")
        nt.assert_array_almost_equal(self.xh_expected[:, 0, 0], xh, 5)

    def test_interp_sigma_to_hybrid_3d(self) -> None:
        xh = interp_sigma_to_hybrid(self.u,
                                    self.sigma,
                                    self.ps,
                                    self.hyam,
                                    self.hybm,
                                    p0=_p0,
                                    method="linear")
        nt.assert_array_almost_equal(self.xh_expected, xh, 5)

    def test_interp_sigma_to_hybrid_3d_transposed(self) -> None:
        xh = interp_sigma_to_hybrid(self.u.transpose('ycoord', 'sigma',
                                                     'xcoord'),
                                    self.sigma,
                                    self.ps.transpose('ycoord', 'xcoord'),
                                    self.hyam,
                                    self.hybm,
                                    p0=_p0,
                                    method="linear")
        nt.assert_array_almost_equal(
            self.xh_expected.transpose('ncl2', 'ncl3', 'ncl1'), xh, 5)

    def test_interp_sigma_to_hybrid_3d_dask(self) -> None:

        ps_dask = self.ps.chunk()
        u_dask = self.u.chunk()

        xh = interp_sigma_to_hybrid(u_dask,
                                    self.sigma,
                                    ps_dask,
                                    self.hyam,
                                    self.hybm,
                                    p0=_p0,
                                    method="linear")
        nt.assert_array_almost_equal(self.xh_expected, xh, 5)

    def test_interp_sigma_to_hybrid_wrong_method(self) -> None:
        with pytest.raises(ValueError):
            xh = interp_sigma_to_hybrid(self.u,
                                        self.sigma,
                                        self.ps,
                                        self.hyam,
                                        self.hybm,
                                        p0=_p0,
                                        method="wrong_method")


class Test_interp_manually_calc:

    @pytest.fixture(scope="class")
    def test_input(self):
        return xr.load_dataset(
            gdf.get("netcdf_files/interpolation_test_input_data.nc"))

    @pytest.fixture(scope="class")
    def test_output(self):
        return xr.load_dataset(
            gdf.get("netcdf_files/interpolation_test_output_data.nc"))

    @pytest.fixture(autouse=True, scope="class")
    @classmethod
    def setUpClass(cls, test_input, test_output) -> None:
        cls.data_in = test_input['normal']
        cls.data_out = test_output['normal']

        cls.lat_in = cls.data_in['lat'].values
        cls.lat_out = cls.data_out['lat'].values
        cls.lon_in = cls.data_in['lon'].values
        cls.lon_out = cls.data_out['lon'].values

        cls.data_in_nan = test_input['nan']
        cls.data_out_nan = test_output['nan']

        cls.data_in_nan_2 = test_input['nan_2']
        cls.data_out_nan_2 = test_output['nan_2']

        cls.data_in_missing = test_input['missing']
        cls.data_out_missing = test_output['missing']

        cls.data_in_mask = test_input['mask']
        cls.data_out_mask = test_output['mask']

    def test_float32(self) -> None:
        np.testing.assert_almost_equal(
            self.data_out.values.astype(np.float32),
            interp_multidim(xr.DataArray(self.data_in.values.astype(np.float32),
                                         dims=['lat', 'lon'],
                                         coords={
                                             'lat': self.lat_in,
                                             'lon': self.lon_in,
                                         }),
                            self.lat_out,
                            self.lon_out,
                            cyclic=True).values,
            decimal=7)

    def test_float64(self) -> None:
        np.testing.assert_almost_equal(
            self.data_out.values.astype(np.float64),
            interp_multidim(
                xr.DataArray(self.data_in.values.astype(np.float64),
                             dims=['lat', 'lon'],
                             coords={
                                 'lat': self.lat_in,
                                 'lon': self.lon_in,
                             }),
                self.lat_out,
                self.lon_out,
                cyclic=True,
            ).values,
            decimal=8,
        )

    def test_missing(self) -> None:
        np.testing.assert_almost_equal(
            self.data_out_missing,
            interp_multidim(
                self.data_in_missing,
                self.lat_out,
                self.lon_out,
                cyclic=True,
            ).values,
            decimal=8,
        )

    def test_nan(self) -> None:
        np.testing.assert_almost_equal(
            self.data_out_nan,
            interp_multidim(
                self.data_in_nan,
                self.lat_out,
                self.lon_out,
                cyclic=True,
            ).values,
            decimal=8,
        )

    def test_mask(self) -> None:
        np.testing.assert_almost_equal(
            self.data_out_mask,
            interp_multidim(
                self.data_in_mask,
                self.lat_out,
                self.lon_out,
                cyclic=True,
            ).values,
            decimal=8,
        )

    def test_2_nans(self) -> None:
        np.testing.assert_almost_equal(
            self.data_out_nan_2,
            interp_multidim(
                self.data_in_nan_2,
                self.lat_out,
                self.lon_out,
                cyclic=True,
            ).values,
            decimal=8,
        )

    def test_numpy(self) -> None:
        np.testing.assert_almost_equal(self.data_out.values,
                                       interp_multidim(
                                           self.data_in.values,
                                           self.lat_out,
                                           self.lon_out,
                                           lat_in=self.lat_in,
                                           lon_in=self.lon_in,
                                           cyclic=True,
                                       ),
                                       decimal=8)

    def test_extrapolate(self) -> None:
        np.testing.assert_almost_equal(self.data_out.values,
                                       interp_multidim(
                                           self.data_in,
                                           self.lat_out,
                                           self.lon_out,
                                           cyclic=True,
                                           fill_value='extrapolate',
                                       ),
                                       decimal=8)


class Test_interp_larger_dataset:

    @pytest.fixture(scope="class")
    def test_input(self):
        return xr.load_dataset(
            gdf.get("netcdf_files/spherical_noise_input.nc"))['spherical_noise']

    @pytest.fixture(scope="class")
    def test_output(self):
        return xr.load_dataset(gdf.get(
            "netcdf_files/spherical_noise_output.nc"))['spherical_noise']

    @pytest.fixture(autouse=True, scope="class")
    @classmethod
    def setUpClass(cls, test_input) -> None:
        cls.test_output = None
        cls.test_lat_output = None
        cls.test_lon_output = None
        cls.test_data_chunked = None
        cls.test_data_chunked = test_input.chunk(2)

    def test_10x(self, test_input, test_output) -> None:
        data_xr = interp_multidim(test_input, test_output.coords['lat'],
                                  test_output.coords['lon'])
        np.testing.assert_almost_equal(
            test_output,
            data_xr.values,
            decimal=8,
        )

    def test_chunked(self, test_output) -> None:
        data_xr = interp_multidim(self.test_data_chunked,
                                  test_output.coords['lat'],
                                  test_output.coords['lon'])

        np.testing.assert_almost_equal(test_output, data_xr.values, decimal=8)
