import sys
import unittest

import dask.array as da
import dask.distributed as dd
import numpy as np
import xarray as xr

# Import from directory structure if coverage test, or from installed
# packages otherwise
if "--cov" in str(sys.argv):
    from src.geocat.comp import heat_index
else:
    from geocat.comp import heat_index


class Test_heat_index(unittest.TestCase):

    @classmethod
    def setUpClass(cls):

        # get ground truth from ncl run netcdf file
        try:
            ncl_xr_gt = xr.open_dataarray(
                "heat_index_output.nc"
            )  # Generated by running ncl_tests/test_max_daylight.ncl
        except:
            ncl_xr_gt = xr.open_dataarray("test/test_heat_output.nc")

        # set up ground truths
        cls.ncl_gt = np.asarray(ncl_xr_gt)

        cls.jday_gt = np.linspace(1, 365, num=365)
        cls.lat_gt = np.linspace(-66, 66, num=133)

        # make client to reference in subsequent tests
        cls.client = dd.Client()