# .github/release.yml

changelog:
  categories:
    - title: New Features
      labels:
        - feature
    - title: Enhancements
      labels:
        - enhancement
    - title: Deprecations
      labels:
        - deprecation
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
        - tutorial
    - title: Maintenance
      labels:
        - developer feature
        - refactor
        - testing
    - title: Misc
      labels:
        - "*"
