{% set name = "geocat-comp" %}
{% set version = "2022.03.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  skip: true  # [py<38 or win]

source:
  # url: https://github.com/NCAR/{{ name }}/archive/v{{ version }}.tar.gz # For building from a specific tag's tarball
  # sha256: ec73166e12f20867821365ef8467d970288132093f7a680c206ab2d661d61c4d
  git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: main # For building from branch for debugging purposes
  git_url: https://github.com/NCAR/{{ name }}.git

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - geocat-f2py                         # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - geocat-f2py
  run:
    - python
    - cf_xarray>=0.3.1
    - cftime
    - dask
    - eofs
    - geocat-f2py
    - metpy
    - numpy
    - scipy
    - xarray

test:
  requires:
    - pytest
    - netcdf4
    - geocat-datafiles
  imports:
    - geocat
    - geocat.comp
  commands:
    - pytest test
  source_files:
    - test

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-comp is a Python package containing a subset of NCL (NCAR Command Language) computational routines.
  dev_url: https://github.com/NCAR/geocat-f2py
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pilotchute # A. Kootz https://github.com/pilotchute
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - anissa111 # A. Zacharias https://github.com/anissa111
    - michaelavs # M. Sizemore https://github.com/michaelavs
