{% set name = "geocat-comp" %}
{% set version = "2023.02.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

source:
  git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: main # For building from branch for debugging purposes
  git_url: https://github.com/NCAR/{{ name }}.git

requirements:
  build:
    - python>=3/8, <3.11                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - geocat-f2py                         # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - geocat-f2py
  run:
    - python
    - cf_xarray>=0.3.1
    - cftime
    - dask
    - eofs
    - geocat-f2py
    - metpy
    - numpy
    - scipy
    - xarray
    - xskillscore

test:
  requires:
    - pytest
    - netcdf4
    - geocat-datafiles
  imports:
    - geocat
    - geocat.comp
  commands:
    - pytest test
  source_files:
    - test

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-comp is a Python package containing a subset of NCL (NCAR Command Language) computational routines.
  dev_url: https://github.com/NCAR/geocat-f2py
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pilotchute # A. Kootz https://github.com/pilotchute
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - anissa111 # A. Zacharias https://github.com/anissa111
    - hcraker # H. Craker https://github.com/hcraker
    - jukent # J. Kent https://github.com/jukent
