name: 🐛 Bug report
description: File a bug report
title: '[🐛]: '
labels: ['bug', 'support', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of geocat-comp are you running?
      placeholder: "v2024.01.0"
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: How did you install geocat-comp?
      multiple: false
      options:
        - conda-forge
        - pip
        - source
        - pre-made maintained environment
        - other (please explain in your summary below)
    validations:
      required: true

  - type: textarea
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Example: macOS Big Sur"
      value: operating system
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Please provide a summary of the issue"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: "Steps to reproduce"
      description: "If possible, please provide a minimally reproducible example to reproduce the problem"
    validations:
      required: false

  - type: textarea
    id: stack
    attributes:
      label: "Stack trace"
      description: "If applicable, please provide a stack trace"
    validations:
        required: false

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "If possible, please paste the output of `conda list` or `pip freeze` here"
    validations:
      required: false
