
blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request Google Form
    url: https://forms.gle/6DTo3ELLri4DAGfG8
    about: |
      Alternatively, you can also submit any feature requests through the Feature Request Form
