name: Release Request
description: Request a version bump and release
title: "[Release]: <version-number>"
labels: ["release", "high priority"]
assignees:
  - pilotchute
body:
  - type: markdown
    attributes:
      value: |
          - [ ] version number has been updated in meta.yaml
          - [ ] release-notes.rst has been updated with latest release notes
          - [ ] a new tag and release has been made on GitHub
          - [ ] feedstock PR has been merged
  - type: input
    id: version-number
    attributes:
      label: New Version Number
      description: What is the version number for the release?
      placeholder: vYYYY.MM.##
    validations:
      required: true
